#!/bin/sh

if [ $# -ne 3 ]
then
    echo "Usage: `basename $0` <executable name> <map file> <scen file>"
    exit $E_BADARGS
fi
mkdir -p ../results
#./`basename $1` -run $2 $3 | awk '{sum +=$3} END{print sum}'
./`basename $1` -run $2 $3 > ../result/$1-$3.out

# ./main -run Aftershock.map Aftershock.map.scen | awk '{sum +=$3} END{print sum}'
