#!/bin/bash

printBenchmarkTest()
{
    printf "BENCHMARK\tprogram\t$1\tmap\t$2\tscenario\t$3\ttime$2\t\n"
    ./benchmarkTest $1 $2 $3

}


printBenchmarkTest astar_colorized_class Aftershock.map shortAftershock.map.scen
printBenchmarkTest astar_colorized_class Aftershock.map longAftershock.map.scen


printBenchmarkTest astar_colorized_functions Aftershock.map shortAftershock.map.scen
printBenchmarkTest astar_colorized_functions Aftershock.map longAftershock.map.scen

printBenchmarkTest astar_nocolor Aftershock.map  shortAftershock.map.scen
printBenchmarkTest astar_nocolor Aftershock.map longAftershock.map.scen

printBenchmarkTest dijkstra_bucket Aftershock.map shortAftershock.map.scen
printBenchmarkTest dijkstra_bucket Aftershock.map longAftershock.map.scen

printBenchmarkTest dijkstra_stdheap Aftershock.map shortAftershock.map.scen
printBenchmarkTest dijkstra_stdheap Aftershock.map longAftershock.map.scen

printBenchmarkTest anderson Aftershock.map shortAftershock.map.scen
printBenchmarkTest anderson Aftershock.map longAftershock.map.scen
