#!/bin/bash

printBenchmarkTest()
{
    printf "BENCHMARK\tprogram\t$1\tmap\t$2\tscenario\t$3\ttime$2\t\n"
    ./benchmarkTest $1 $2 $3

}


printBenchmarkTest astar_colorized_class maze-400-4.map shortmaze-400-4.map.scen
printBenchmarkTest astar_colorized_class maze-400-4.map longmaze-400-4.map.scen


printBenchmarkTest astar_colorized_functions maze-400-4.map shortmaze-400-4.map.scen
printBenchmarkTest astar_colorized_functions maze-400-4.map longmaze-400-4.map.scen

printBenchmarkTest astar_nocolor maze-400-4.map  shortmaze-400-4.map.scen
printBenchmarkTest astar_nocolor maze-400-4.map longmaze-400-4.map.scen

printBenchmarkTest dijkstra_bucket maze-400-4.map shortmaze-400-4.map.scen
printBenchmarkTest dijkstra_bucket maze-400-4.map longmaze-400-4.map.scen

printBenchmarkTest dijkstra_stdheap maze-400-4.map shortmaze-400-4.map.scen
printBenchmarkTest dijkstra_stdheap maze-400-4.map longmaze-400-4.map.scen

printBenchmarkTest anderson maze-400-4.map shortmaze-400-4.map.scen
printBenchmarkTest anderson maze-400-4.map longmaze-400-4.map.scen
