#!/bin/bash

printBenchmarkTest()
{
    printf "BENCHMARK\tprogram\t$1\tmap\t$2\tscenario\t$3\ttime$2\t\n"
    ./benchmarkTest $1 $2 $3

}


printBenchmarkTest astar_colorized_class BigGameHunters.map shortBigGameHunters.map.scen
printBenchmarkTest astar_colorized_class BigGameHunters.map longBigGameHunters.map.scen


printBenchmarkTest astar_colorized_functions BigGameHunters.map shortBigGameHunters.map.scen
printBenchmarkTest astar_colorized_functions BigGameHunters.map longBigGameHunters.map.scen

printBenchmarkTest astar_nocolor BigGameHunters.map  shortBigGameHunters.map.scen
printBenchmarkTest astar_nocolor BigGameHunters.map longBigGameHunters.map.scen

printBenchmarkTest dijkstra_bucket BigGameHunters.map shortBigGameHunters.map.scen
printBenchmarkTest dijkstra_bucket BigGameHunters.map longBigGameHunters.map.scen

printBenchmarkTest dijkstra_stdheap BigGameHunters.map shortBigGameHunters.map.scen
printBenchmarkTest dijkstra_stdheap BigGameHunters.map longBigGameHunters.map.scen

printBenchmarkTest anderson BigGameHunters.map shortBigGameHunters.map.scen
printBenchmarkTest anderson BigGameHunters.map longBigGameHunters.map.scen
