#!/bin/bash

printBenchmarkTest()
{
    printf "BENCHMARK\tprogram\t$1\tmap\t$2\tscenario\t$3\ttime$2\t\n"
    ./benchmarkTest $1 $2 $3

}

printBenchmarkTest astar_colorized_functions Aftershock.map shortAftershock.map.scen
printBenchmarkTest astar_colorized_functions Aftershock.map longAftershock.map.scen

printBenchmarkTest astar_colorized_functions Brushfire.map shortBrushfire.map.scen
printBenchmarkTest astar_colorized_functions Brushfire.map longBrushfire.map.scen

printBenchmarkTest dijkstra_stdheap Brushfire.map shortBrushfire.map.scen
printBenchmarkTest dijkstra_stdheap Brushfire.map longBrushfire.map.scen

printBenchmarkTest dijkstra_stdheap Aftershock.map shortAftershock.map.scen
printBenchmarkTest dijkstra_stdheap Aftershock.map longAftershock.map.scen